config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users do
    delete "/logout" => "devise/sessions#destroy", :as => :destroy_user_session
  end
  
  resources :posts
  resources :users
  

end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

	has_many :posts, :dependent => :destroy
	has_many :comments, :dependent => :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :authenticate_user!
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
  	@posts = Post.all
  end

  def new
	if user_signed_in?
	@post = Post.new
	else
	redirect_to new_user_session_path
	end
end

 def create
	@post = Post.new(post_params)
	if @post.save
		redirect_to posts_path
	else
		render 'new'
	end
end

 def edit
@post = Post.find(params[:id])
 end

def show
@post = Post.find(params[:id])
end	

def destroy
@post = Post.find(params[:id])
@post.destroy
redirect_to posts_path
end


def update
 @post = Post.find(params[:id])
 if @post.update_attributes(post_params)
  redirect_to post_path(@post.id)
 else
  render 'edit'
 end
end

 private
	def post_params
	params.require(:post).permit(:title, :body, :latitude, :longitude, :user_id)
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

def new
    @user = User.new
end

def create
    @user = User.new(user_params)
    if @user.save
    redirect_to users_path
    else
    render 'new'
    end
end

  def index
    @users=User.all
  end

def edit
@user = User.find(params[:id])
end

def destroy
    @user = User.find(params[:id])
    if @user == current_user
    @user.destroy
    redirect_to users_path
	else
	redirect_to :back, :alert => "Access Denied"
	end
end

def update
 @user = User.find(params[:id])
 if @user.update_attributes(user_params)
  redirect_to user_path(@user.id)
 else
  render 'edit'
 end
end

def show
    @user = User.find(params[:id])
end

private

    def user_params
        params.require(:user).permit(:name, :email, :password)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HealthTracker</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%#= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  
  <%= csrf_meta_tags %>
</head>
<body>
	<nav class="navbar navbar-default" role="navigation">
	  <div class="container">
		    <div class="navbar-header">
			    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
			        <span class="sr-only">Toggle navigation</span>
			        <span class="icon-bar"></span>
			        <span class="icon-bar"></span>
			        <span class="icon-bar"></span>
		      	</button>
	      <a class="navbar-brand" href="/">HealthTracker</a>
	    </div>
	    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><%= link_to 'Users', users_path %><span class="sr-only">(current)</span></li>
        <li><%= link_to 'Posts', posts_path%></li>
          </ul>
    </div><!-- /.navbar-collapse -->
	  </div>
	</nav>
<%= yield %>

</body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="field">
<p>title</p>
<%= f.text_field :title %>
</div>

<div class="field">
<p>body</p>
<%= f.text_area :body %>
</div>


<div class="field">
<p>latitude</p>
<%= f.text_field :latitude %>
</div>


<div class="field">
<p>longitude</p>
<%= f.text_field :longitude %>
</div>

<div class="field">
<p>user</p>
<%= f.collection_select :user_id, User.all, :id, :name %>
</div>

<div class="actions">
<%= f.submit %>
</div>
<% end %>	

app/views/posts/edit.html.erb
<h1>Posts#edit</h1>
<p>Find me in app/views/posts/edit.html.erb</p>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<div class="container-fluid">
<h1>Posts</h1>

<table>
<tr>
<td>Disease</td>
<td>Comments</td>
<td>Latitude</td>
<td>Longitude</td>
<td>User</td>
</tr>
<% @posts.each do |post| %>
<tr>
	<td><%= post.title %></td>
	<td><%= post.body %></td>
	<td><%= post.latitude %></td>
	<td><%= post.longitude %></td>
	<td><%= post.user.name %></td>
	<td><%= link_to post.title, post_path(post) %></td>

</tr>
<% end %>
</table>
</div>

app/views/posts/new.html.erb
<h1>Posts#new</h1>
<p>Find me in app/views/posts/new.html.erb</p>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>

<div>
<h2><%= @post.title %></h2>
<p><%= @post.body %></p>
<p><%= @post.latitude %></p>
<p><%= @post.longitude %></p>
<p><%= @post.user.name %></p>
</div>
<%= link_to 'Back', posts_path %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <div class="field">
        <p>name</p> 
        <%= f.text_field :name%>
    </div>
    <div class="field">
        <p>email</p> 
        <%= f.text_field :email%>
    </div>
    <div class="field">
        <p>password</p> 
        <%= f.text_field :password%>
    </div>
    <div class="actions">
        <%= f.submit %>
    </div>
  <% end %>

app/views/users/delete.html.erb
<h1>Users#delete</h1>
<p>Find me in app/views/users/delete.html.erb</p>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

<table>
 	<tr>
 		<td>name</td>
 		<td>email</td>
 		<td>password</td>
 	</tr>
 	<% @users.each do |user| %>
 	<tr>
 		<td><%= link_to user.name, user_path(user.id) %></td>
 		<td><%= user.email %></td>
 		<td><%= user.password %></td>
 		<td><%= link_to "edit user", edit_user_path(user.id) %> </td>
 		<td><%= link_to "Delete", user_path(user), :confirm => "Are you sure?", :method => :delete %></td>
 		<td><%= link_to "Delete User", registration_path(user), data: { confirm: "Are you sure?" }, method: :delete %> </td>
 	</tr>:


 	<% end %>

</table>

<br>
<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

 <%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/posts/users.html.erb</p>

<div>
<h2><%= @user.name %></h2>
<p><%= @user.email %></p>
<p><%= @user.password %></p>
</div>
<%= link_to 'Back', users_path %>